### ISSUE TITLE
Zero() function

### ISSUE THREAD

**Issue by SolarLune** [kvartborg/vector#4]
Hello! 

I'm finding your vector library useful; thanks a lot for making it. I like how it feels "Go-like", in that it directly repurposes arrays and is as "simple" as possible.

I wanted to ask to see if it would be possible to add a Zero function to easily zero out a vector of arbitrary size (or maybe a `Set` function to set all components to the same value). Of course, I would be fine to submit a PR for this if you would find it useful as well.

**Comment by kvartborg** [comment]
Hello!

I'm happy to hear that you find it useful and for your interest for this project. 😄 

Before i make a decision about whether this should be added this or not, i would like if you could elaborate on the use case for the `Zero` or `Set` function?
As i understand your question, it is for zeroing out an existing vector right? 
Why is this better than just creating a new instance of a zero vector? 
Is it because of performance and memory usage concerns?

**Comment by SolarLune** [comment]
Not for performance or memory usage, but just for syntactic sugar, honestly.

**Comment by kvartborg** [comment]
The reason I’m a bit hesitant with the `Zero` function is that it is often used to instantiate zero vectors in other libraries, repurposing it might cause confusion. And it is not needed as I see it, because Go already support an easy way to create zero vectors without the need for any constructor functions. 

```go
z := make(vec, 2)
```

I will close this issue for now. But feel free to open a new one if you have a good example for a use case for it.
